//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordGenLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordGenLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a baculo
        ///a bene placito
        ///a bit
        ///a building
        ///a burton
        ///a capella
        ///a cappella
        ///a capriccio
        ///a cock horse
        ///a damn sight
        ///a day after the fair
        ///a fortiori
        ///a fuck sight
        ///a go go
        ///a good deal
        ///a great deal
        ///a hold
        ///a la mode
        ///a little
        ///a little bit
        ///a little matter
        ///a lot
        ///a lot of bit
        ///a matter
        ///a mensa et thoro
        ///a mite
        ///a mornings
        ///a piacere
        ///a plenty
        ///a posteriori
        ///a priori
        ///a row
        ///a small matter
        ///a smidgen
        ///a tad
        ///a tilt
        ///a to z
        ///a treat
        ///a trifle
        ///a vie
        ///a vinculo matrimonii
        ///aachen
        ///aahed
        ///aahing
        ///aaland        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string from_lexems {
            get {
                return ResourceManager.GetString("from_lexems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whats up
        ///hey man
        ///hey there
        ///home sweet home
        ///monkey business
        ///head over heels
        ///up in arms
        ///scrape the barrel
        ///scraping the barrel
        ///working out
        ///worked out
        ///works out
        ///gym rat
        ///bend over backwards
        ///blue moon
        ///one in a blue moon
        ///same breath
        ///in the same breath
        ///hot cakes
        ///circle the wagons
        ///carcling the wagons
        ///cloud nine
        ///flip side
        ///stay the course
        ///broad daylight
        ///daylight savings
        ///kid gloves
        ///silver lining
        ///silver linings
        ///hit the sack
        ///burning bridges
        ///cut corners
        ///boil the ocean
        ///snowball effect
        ///aval [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phrases {
            get {
                return ResourceManager.GetString("phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaglung
        ///aalsmeer
        ///aarsdale
        ///abachikkanahalli
        ///abampere
        ///abandanak
        ///abatur
        ///abbahu
        ///abbigirihosahalli
        ///abbotspoort
        ///abderus
        ///abel
        ///aberaman
        ///aberangell
        ///aberargie
        ///abercarn
        ///abercraf
        ///aberdale
        ///abergwesyn
        ///abernyte
        ///abhenry
        ///abiabad
        ///abisare
        ///abkhizeh
        ///ablinga
        ///abqah
        ///abrud
        ///absurdity
        ///abutalipovo
        ///acanthoceratidae
        ///acast
        ///acateno
        ///acciaroli
        ///acenaphthylene
        ///acerra
        ///acetabularia
        ///acetothiolutamide
        ///achammanahalli
        ///achaphubuil
        ///acherontisuchus
        ///acheroraptor
        ///acinaces
        ///acronicta
        ///acteonoidea
        ///activia
        ///acuvue        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wikipedia {
            get {
                return ResourceManager.GetString("wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aah
        ///aardvark
        ///aaron
        ///aba
        ///abalone
        ///abase
        ///abate
        ///abated
        ///abatement
        ///abating
        ///abba
        ///abbasid
        ///abbey
        ///abbreviated
        ///abbreviation
        ///abc
        ///abdomen
        ///abdominal
        ///aberdeen
        ///aberrant
        ///aberration
        ///abeyance
        ///abhor
        ///abhorred
        ///abhorrent
        ///abigail
        ///ablation
        ///ablaze
        ///able
        ///ablution
        ///ably
        ///abnormal
        ///abnormality
        ///abnormally
        ///abnormity
        ///abo
        ///aboard
        ///abolish
        ///abolishment
        ///abolition
        ///abolitionist
        ///aboriginal
        ///aborigine
        ///abound
        ///abounding
        ///about
        ///above
        ///aboveboard
        ///abrade
        ///abraham
        ///abram
        ///abreaction
        ///abreast
        ///abri
        ///abridge
        ///abrogat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
